### PR TITLE
added paper size selection control to make-step-3 UI

### PR DESCRIPTION
**Pull request by brendancol**
I have added in a selector control for the different page sizes I saw indicated in decoder/compose.py.  I've tested Letter, A4, and A3 and they look good.

image

### CODE REVIEW

**Comment by brendancol** [comment]
Could be good to move to step-2 and display correct paper size on map. But for now this is something.

**Comment by mojodna** [comment]
I was holding off on merging this until I could verify that the scanner deals with these correctly.  It does.

**Comment by brendancol** [comment]
Hey Seth,

Sounds good. Project on my side has cooled down a bit, but hoping the
client will re-engage soon.

-Brendan

On Wed, Apr 29, 2015 at 11:45 AM, Seth Fitzsimmons <notifications@github.com

**Comment by mojodna** [comment]
Sweet.  We're making good headway here: https://github.com/fieldpapers, periodically documented here: http://fieldpapers.tumblr.com/, and we lurk in public here (no activity yet 'cause it's just us): https://gitter.im/fieldpapers

**Pull request merged**
